"""empty message

Revision ID: abeac8a5375d
Revises: d7bc1899cadd
Create Date: 2023-07-03 20:42:58.000118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abeac8a5375d'
down_revision = 'd7bc1899cadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_first_name')
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.drop_index('ix_user_last_name')
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.create_index('ix_user_last_name', ['last_name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.create_index('ix_user_first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
